import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navabar";


export const metadata: Metadata = {
  title: "Music app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className="bg-black">
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
